name: GraalVM Build
on:
  push:
    branches: ["main"]

jobs:
  setup-graalvm-ce:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      - name: version
        run: |
          java -version
          native-image --version
          native-image -jar lib/discord-rpc.jar imgscaler
