name: Stupid Tester
on:
  push: 
    branches: ["main"]
  
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  stupid-tester-lets-go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3
      - name: Run run.sh standard
        run: bash run.sh
