on: push
jobs:
  halcyon-deployer:
    runs-on: self-hosted
    steps:
    - name: Cloning the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: Prettify Code
      uses: lwerner-lshigh/prettier_action_java@v1.1.1
      with:
        prettier_options: '--no-semi --write *.java'
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
